# -*- coding: utf-8 -*-
"""Emit the compatibility tables as SQL, from the Swift.

The nightly matcher runs in Postgres, so the 95 numbers have to exist there too.
That is a second copy, and a second copy is a thing that drifts -- so it is
generated rather than written, from the same parse `matcher/tables.py` already does
of `Arch/Mock/Compatibility.swift`.

    python sqlgen.py            write backend/005_compatibility.sql
    python sqlgen.py --digest   print the digests, to compare against the database

**`--digest` is the anti-drift device.** It recomputes both fingerprints from the
Swift; one `select` against the live database says whether what is deployed still
matches. Run it after any edit to `Compatibility.swift`. Without it, "the SQL and
the Swift agree" is an intention rather than a check, and the failure mode is a
matcher that pairs people correctly against the wrong numbers.
"""
import hashlib
import io
import os
import sys

import tables

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "backend", "005_compatibility.sql")

#: Scored questions in questionnaire order, and the three that filter.
SCORED = [q["id"] for q in tables.QUESTIONS if q["rule"] != "requirement"]
REQS = [q["id"] for q in tables.QUESTIONS if q["rule"] == "requirement"]


def milli(weight, cell):
    """`weight * cell` in thousandths, by integer arithmetic only.

    Weights carry one decimal and cells two, so `(weight*10) * (cell*100)` is the
    exact product in thousandths. Multiplying the floats and rounding would work
    almost always, which is the worst property a conversion can have.
    """
    return int(round(weight * 10)) * int(round(cell * 100))


def cells():
    """[(question_id, a, b, milli)] for the thirteen scored grids."""
    out = []
    for qid in SCORED:
        table = tables.TABLES[qid]
        grid = table["grid"]
        for a in range(len(grid)):
            for b in range(len(grid)):
                out.append((qid, a, b, milli(table["weight"], grid[a][b])))
    return out


def requirements():
    """[(question_id, a, b, allowed)] for the three filters."""
    out = []
    for qid in REQS:
        grid = tables.REQUIREMENTS[qid]
        for a in range(len(grid)):
            for b in range(len(grid)):
                out.append((qid, a, b, bool(grid[a][b])))
    return out


def digests():
    """A fingerprint of the numbers, and one of the file they came from.

    The cell digest is what the database can recompute about itself. The source
    digest catches an edit to `Compatibility.swift` that happens not to change any
    number -- a reworded comment is harmless, but knowing which kind of change
    happened is the difference between re-reading a diff and re-reading a file.
    """
    lines = ["%s|%d|%d|%d" % row for row in sorted(cells())]
    lines += ["%s|%d|%d|%s" % (q, a, b, "t" if v else "f")
              for q, a, b, v in sorted(requirements())]
    cell_digest = hashlib.sha256("\n".join(lines).encode("utf-8")).hexdigest()
    with open(tables.COMPATIBILITY, "rb") as handle:
        source_digest = hashlib.sha256(handle.read()).hexdigest()
    return cell_digest, source_digest


HEADER = '''-- Arch: the compatibility tables, in the database.
--
-- **Generated by `matcher/sqlgen.py`. Do not edit by hand.**
--
-- `Arch/Mock/Compatibility.swift` is the single source of truth for the 95
-- hand-written numbers. The nightly matcher runs in Postgres and needs them here
-- too, which makes this a second copy -- so it is generated from the same parse
-- `matcher/tables.py` performs, and fingerprinted so drift is detectable rather
-- than merely unlikely.
--
-- To check the deployed numbers still match the Swift:
--
--     python matcher/sqlgen.py --digest
--     select digest, source_digest from compatibility_digest;
--
-- **Values are integer thousandths, not floats.** Floating-point addition is not
-- associative and a score is a sum of thirteen terms; measured against this
-- population, 54% of scores differ between forward and reverse summation of the
-- identical terms, which moved half the delivered pairs. Every `weight * cell` is
-- exact at 1/1000, so integers lose nothing and make the SQL and the simulation
-- comparable exactly rather than approximately.

create table if not exists compatibility_cells (
    question_id text not null check (question_id ~ '^q([1-9]|1[0-3])$'),
    a smallint not null check (a >= 0),
    b smallint not null check (b >= 0),
    -- weight * grid[a][b], in thousandths. Ceiling is 1.4 * 1.00.
    milli integer not null check (milli between 0 and 1400),
    primary key (question_id, a, b)
);

create table if not exists requirement_cells (
    question_id text not null check (question_id in ('q14','q15','q16')),
    a smallint not null check (a >= 0),
    b smallint not null check (b >= 0),
    -- A filter, never a weight. The moment a good score can buy its way past one,
    -- those three questions stop meaning anything.
    allowed boolean not null,
    primary key (question_id, a, b)
);

create table if not exists compatibility_digest (
    only_row boolean primary key default true check (only_row),
    digest text not null,
    source_digest text not null,
    generated_at timestamptz not null default now()
);

-- Read by the matcher, which runs as the table owner. No client has any business
-- with these: a client that could read them could compute its own score, and Arch
-- shows no scores to anybody.
alter table compatibility_cells enable row level security;
alter table requirement_cells enable row level security;
alter table compatibility_digest enable row level security;

truncate compatibility_cells, requirement_cells, compatibility_digest;

'''


def write():
    scored = cells()
    reqs = requirements()
    cell_digest, source_digest = digests()

    body = [HEADER]

    # Emitted as grids rather than as 158 flat rows, so this file can be read
    # beside `Compatibility.swift` and compared by eye. `generate_subscripts`
    # unrolls them into cells on the way in.
    body.append(
        "-- Thirteen grids, in questionnaire order, each the shape it has in the\n"
        "-- Swift. Row is your answer, column is theirs; symmetric by construction.\n"
        "insert into compatibility_cells (question_id, a, b, milli)\n"
        "select g.q, (i - 1)::smallint, (j - 1)::smallint, g.m[i][j]\n"
        "from (values\n")
    rows = []
    for qid in SCORED:
        table = tables.TABLES[qid]
        grid = table["grid"]
        inner = ",".join(
            "[" + ",".join("%d" % milli(table["weight"], cell) for cell in row) + "]"
            for row in grid)
        rows.append(("    ('%-4s array[%s])" % (qid + "',", inner),
                     "weight %.1f" % table["weight"]))
    # The separator goes before the comment, not after it. A trailing `-- weight
    # 0.8,` swallows the comma into the comment and the statement stops parsing --
    # which is what the first draft of this generator did.
    body.append("\n".join(
        sql + ("," if k < len(rows) - 1 else "") + "  -- " + note
        for k, (sql, note) in enumerate(rows)))
    body.append(
        "\n) as g(q, m),\n"
        "lateral generate_subscripts(g.m, 1) as i,\n"
        "lateral generate_subscripts(g.m, 2) as j;\n\n")

    body.append(
        "-- The three that filter instead of scoring. In every one of them only the\n"
        "-- flat contradiction is barred: \"still working it out\" is compatible with\n"
        "-- everybody, which is the point of having the option at all.\n"
        "insert into requirement_cells (question_id, a, b, allowed)\n"
        "select g.q, (i - 1)::smallint, (j - 1)::smallint, g.m[i][j]\n"
        "from (values\n")
    rows = []
    for qid in REQS:
        grid = tables.REQUIREMENTS[qid]
        inner = ",".join(
            "[" + ",".join("true" if cell else "false" for cell in row) + "]"
            for row in grid)
        rows.append("    ('%-4s array[%s])" % (qid + "',", inner))
    body.append(",\n".join(rows))
    body.append(
        "\n) as g(q, m),\n"
        "lateral generate_subscripts(g.m, 1) as i,\n"
        "lateral generate_subscripts(g.m, 2) as j;\n\n")

    body.append(
        "insert into compatibility_digest (digest, source_digest) values\n"
        "    ('%s',\n     '%s');\n\n" % (cell_digest, source_digest))

    # Checks that run as part of applying the migration, so a bad generation is a
    # failed migration rather than a matcher that quietly scores against nothing.
    body.append('''do $$
declare
    n_cells int;
    n_reqs int;
    bad int;
begin
    select count(*) into n_cells from compatibility_cells;
    select count(*) into n_reqs from requirement_cells;
    if n_cells <> %d then
        raise exception 'expected %d scored cells, found %%', n_cells;
    end if;
    if n_reqs <> %d then
        raise exception 'expected %d requirement cells, found %%', n_reqs;
    end if;

    -- Every grid square: a question with n options must have exactly n*n cells.
    select count(*) into bad from (
        select question_id, count(*) c, max(a) ma, max(b) mb
        from compatibility_cells group by question_id
    ) g where g.c <> (g.ma + 1) * (g.mb + 1) or g.ma <> g.mb;
    if bad > 0 then
        raise exception '%% compatibility grids are not square', bad;
    end if;

    -- Every grid symmetric. Asymmetry would mean the score depended on which of
    -- two people the matcher happened to ask about first.
    select count(*) into bad
      from compatibility_cells x join compatibility_cells y
        on y.question_id = x.question_id and y.a = x.b and y.b = x.a
     where y.milli <> x.milli;
    if bad > 0 then
        raise exception '%% compatibility cells are asymmetric', bad;
    end if;

    select count(*) into bad
      from requirement_cells x join requirement_cells y
        on y.question_id = x.question_id and y.a = x.b and y.b = x.a
     where y.allowed <> x.allowed;
    if bad > 0 then
        raise exception '%% requirement cells are asymmetric', bad;
    end if;
end;
$$;
''' % (len(scored), len(scored), len(reqs), len(reqs)))

    io.open(OUT, "w", encoding="utf-8", newline="\n").write("".join(body))
    return len(scored), len(reqs), cell_digest, source_digest


def main():
    if "--digest" in sys.argv:
        cell_digest, source_digest = digests()
        print("cells  %s" % cell_digest)
        print("source %s" % source_digest)
        print()
        print("compare against the database with:")
        print("  select digest, source_digest from compatibility_digest;")
        return 0

    n_cells, n_reqs, cell_digest, source_digest = write()
    # The generated numbers must be the ones the simulation actually uses.
    import filters
    mismatch = 0
    for qid, a, b, value in cells():
        j = SCORED.index(qid)
        if filters.WEIGHTED_MILLI[j][a][b] != value:
            mismatch += 1
    if mismatch:
        print("FAILED: %d cells disagree with matcher/filters.py" % mismatch)
        return 1

    print("wrote %s" % os.path.relpath(OUT, ROOT).replace(os.sep, "/"))
    print("  %d scored cells, %d requirement cells" % (n_cells, n_reqs))
    print("  cells  %s" % cell_digest)
    print("  source %s" % source_digest)
    print("  agrees with matcher/filters.py on every cell")
    return 0


if __name__ == "__main__":
    sys.exit(main())
