-- Arch: the compatibility tables, in the database.
--
-- **Generated by `matcher/sqlgen.py`. Do not edit by hand.**
--
-- `Arch/Mock/Compatibility.swift` is the single source of truth for the 95
-- hand-written numbers. The nightly matcher runs in Postgres and needs them here
-- too, which makes this a second copy -- so it is generated from the same parse
-- `matcher/tables.py` performs, and fingerprinted so drift is detectable rather
-- than merely unlikely.
--
-- To check the deployed numbers still match the Swift:
--
--     python matcher/sqlgen.py --digest
--     select digest, source_digest from compatibility_digest;
--
-- **Values are integer thousandths, not floats.** Floating-point addition is not
-- associative and a score is a sum of thirteen terms; measured against this
-- population, 54% of scores differ between forward and reverse summation of the
-- identical terms, which moved half the delivered pairs. Every `weight * cell` is
-- exact at 1/1000, so integers lose nothing and make the SQL and the simulation
-- comparable exactly rather than approximately.

create table if not exists compatibility_cells (
    question_id text not null check (question_id ~ '^q([1-9]|1[0-3])$'),
    a smallint not null check (a >= 0),
    b smallint not null check (b >= 0),
    -- weight * grid[a][b], in thousandths. Ceiling is 1.4 * 1.00.
    milli integer not null check (milli between 0 and 1400),
    primary key (question_id, a, b)
);

create table if not exists requirement_cells (
    question_id text not null check (question_id in ('q14','q15','q16')),
    a smallint not null check (a >= 0),
    b smallint not null check (b >= 0),
    -- A filter, never a weight. The moment a good score can buy its way past one,
    -- those three questions stop meaning anything.
    allowed boolean not null,
    primary key (question_id, a, b)
);

create table if not exists compatibility_digest (
    only_row boolean primary key default true check (only_row),
    digest text not null,
    source_digest text not null,
    generated_at timestamptz not null default now()
);

-- Read by the matcher, which runs as the table owner. No client has any business
-- with these: a client that could read them could compute its own score, and Arch
-- shows no scores to anybody.
alter table compatibility_cells enable row level security;
alter table requirement_cells enable row level security;
alter table compatibility_digest enable row level security;

truncate compatibility_cells, requirement_cells, compatibility_digest;

-- Thirteen grids, in questionnaire order, each the shape it has in the
-- Swift. Row is your answer, column is theirs; symmetric by construction.
insert into compatibility_cells (question_id, a, b, milli)
select g.q, (i - 1)::smallint, (j - 1)::smallint, g.m[i][j]
from (values
    ('q1', array[[800,320,640],[320,720,640],[640,640,720]]),  -- weight 0.8
    ('q2', array[[1000,750,250],[750,1000,750],[250,750,1000]]),  -- weight 1.0
    ('q3', array[[1200,900,300],[900,1200,900],[300,900,1200]]),  -- weight 1.2
    ('q4', array[[600,540,420],[540,600,540],[420,540,600]]),  -- weight 0.6
    ('q5', array[[810,900,450],[900,900,810],[450,810,630]]),  -- weight 0.9
    ('q6', array[[1170,585,1105],[585,1040,1105],[1105,1105,1170]]),  -- weight 1.3
    ('q7', array[[1080,1200,720],[1200,1140,840],[720,840,480]]),  -- weight 1.2
    ('q8', array[[1200,420,840],[420,1200,960],[840,960,1140]]),  -- weight 1.2
    ('q9', array[[1190,1260,420],[1260,1400,1190],[420,1190,1260]]),  -- weight 1.4
    ('q10', array[[1000,850,350],[850,1000,750],[350,750,1000]]),  -- weight 1.0
    ('q11', array[[700,630,490,420],[630,700,595,560],[490,595,560,595],[420,560,595,630]]),  -- weight 0.7
    ('q12', array[[900,540,540],[540,900,450],[540,450,630]]),  -- weight 0.9
    ('q13', array[[800,480,680],[480,800,720],[680,720,800]])  -- weight 0.8
) as g(q, m),
lateral generate_subscripts(g.m, 1) as i,
lateral generate_subscripts(g.m, 2) as j;

-- The three that filter instead of scoring. In every one of them only the
-- flat contradiction is barred: "still working it out" is compatible with
-- everybody, which is the point of having the option at all.
insert into requirement_cells (question_id, a, b, allowed)
select g.q, (i - 1)::smallint, (j - 1)::smallint, g.m[i][j]
from (values
    ('q14', array[[true,false,true,true],[false,true,true,true],[true,true,true,true],[true,true,true,true]]),
    ('q15', array[[true,false,true],[false,true,true],[true,true,true]]),
    ('q16', array[[true,false,true],[false,true,true],[true,true,true]])
) as g(q, m),
lateral generate_subscripts(g.m, 1) as i,
lateral generate_subscripts(g.m, 2) as j;

insert into compatibility_digest (digest, source_digest) values
    ('f5dbac32c72ba545d1992dddf1285d92a066d5baac01688d377063d80aedddd7',
     '9dbd3f643d885f6da9a44d74b7bcf409f2ded034e0a39878b104d464b8a535b6');

do $$
declare
    n_cells int;
    n_reqs int;
    bad int;
begin
    select count(*) into n_cells from compatibility_cells;
    select count(*) into n_reqs from requirement_cells;
    if n_cells <> 124 then
        raise exception 'expected 124 scored cells, found %', n_cells;
    end if;
    if n_reqs <> 34 then
        raise exception 'expected 34 requirement cells, found %', n_reqs;
    end if;

    -- Every grid square: a question with n options must have exactly n*n cells.
    select count(*) into bad from (
        select question_id, count(*) c, max(a) ma, max(b) mb
        from compatibility_cells group by question_id
    ) g where g.c <> (g.ma + 1) * (g.mb + 1) or g.ma <> g.mb;
    if bad > 0 then
        raise exception '% compatibility grids are not square', bad;
    end if;

    -- Every grid symmetric. Asymmetry would mean the score depended on which of
    -- two people the matcher happened to ask about first.
    select count(*) into bad
      from compatibility_cells x join compatibility_cells y
        on y.question_id = x.question_id and y.a = x.b and y.b = x.a
     where y.milli <> x.milli;
    if bad > 0 then
        raise exception '% compatibility cells are asymmetric', bad;
    end if;

    select count(*) into bad
      from requirement_cells x join requirement_cells y
        on y.question_id = x.question_id and y.a = x.b and y.b = x.a
     where y.allowed <> x.allowed;
    if bad > 0 then
        raise exception '% requirement cells are asymmetric', bad;
    end if;
end;
$$;
